[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/careers"
  to = "/index.html"
  status = 200

# Let /favicon.ico be served directly (place a real ICO in public/)

[context.production.environment]
  SITE_URL = "https://swifttruckingllc.com"
